/** Telegram Menu button commands + /help text listing bot commands and PAI skills. */

import type { Bot } from "grammy";

const BOT_COMMANDS: Array<{ command: string; description: string }> = [
  { command: "add", description: "Capture idea to INBOX" },
  { command: "url", description: "Save URL to INBOX" },
  { command: "memo", description: "Save memo to INBOX" },
  { command: "remind", description: "Schedule reminder" },
  { command: "review", description: "Show review queue" },
  { command: "approve", description: "Approve review item n" },
  { command: "discard", description: "Discard review item n" },
  { command: "view", description: "Preview review item n" },
  { command: "projects", description: "List available projects" },
  { command: "project", description: "Switch to project" },
  { command: "memory", description: "List stored memories" },
  { command: "forget", description: "Wipe all stored memory" },
  { command: "update", description: "Self-upgrade the bot" },
  { command: "lock", description: "Lock session" },
  { command: "unlock", description: "Unlock with PIN" },
  { command: "help", description: "Show all commands and skills" },
];

export async function registerBotMenu(bot: Bot): Promise<void> {
  await bot.api.setMyCommands(BOT_COMMANDS).catch((err) => {
    console.warn("[bot] setMyCommands failed:", err instanceof Error ? err.message : err);
  });
}

export const HELP_TEXT = [
  "🎛 BOT COMMANDS",
  "/add /url /memo /remind — capture to INBOX",
  "/review /approve <n> /discard <n> /view <n> — triage queue",
  "/projects /project <name> — switch working project",
  "/memory — list · /memory delete <n> — remove one",
  "/forget — wipe all memory (nuclear)",
  "/lock /unlock <pin> — session lock",
  "/update — self-upgrade bot",
  "/help — this list",
  "",
  "🧠 PAI CORE",
  "Pai — capability discovery, list skills, triggers, agents",
  "Telos — goals, beliefs, reports, dashboards, job search, Bewerbung, CV",
  "Agents — compose custom agents, parallel spawns, traits+voice",
  "Thinking — first principles, brainstorm, red team, council, threat model",
  "context-search / /cs — search prior sessions",
  "",
  "📝 CONTENT",
  "ContentAnalysis — extract wisdom, summarize URL, transcripts,",
  "   YouTube-to-ebook, channel digest, AI builders digest",
  "Research — quick/standard/extensive/deep, Fabric patterns (242+)",
  "Scraping — jina, crawl4ai, spider, bird (X/Twitter),",
  "   discrawl (Discord), katana URL discovery, Apify",
  "Investigation — OSINT, due diligence, people search, public records",
  "",
  "⚙️ DEV",
  "Gsd — spec-driven dev: gsd new / plan / execute / verify / quick /",
  "   progress / pause / resume / autonomous / health / diagnose",
  "TDD — test-first, prove-it pattern, test pyramid, coverage",
  "CodeReview — PR review, 5-axis eval, shellcheck, bash lint",
  "GitWorkflow — commits, worktrees, git-cliff, changelog, save-point",
  "Troubleshooting — 6-step triage, incidents, SEV1/2, postmortems",
  "Documentation — ADR, API docs, JSDoc, OpenAPI, doc health",
  "update-config — settings.json, hooks, permissions, env vars",
  "claude-api — Anthropic SDK, prompt caching, model migration",
  "",
  "🎨 VISUALS",
  "Media — illustrations, diagrams, mermaid, infographics, headers,",
  "   thumbnails, comics, video via Remotion, Midjourney, bg removal",
  "Frontend — UI, HTML, websites, design review, website factory,",
  "   typeset, animate, colorize, audit, site teardown",
  "VisualExplainer — HTML diagrams, slide decks, diff review,",
  "   flowchart HTML, data-table viz, fact-check report",
  "ScientificDeck — LaTeX Beamer, academic slides, rhetoric of decks",
  "",
  "📊 DATA",
  "Data — DuckDB SQL, miller, xsv, gron, jq/yq,",
  "   FRED/EIA/Treasury/BLS economic metrics (68 indicators)",
  "DEMOS — SuperColony publishing, Isidore, DAHR attestation,",
  "   TLSNotary, consensus signals, leaderboard",
  "",
  "🔐 OPS",
  "Security — pentest, OWASP, prompt injection, CVE/Trivy scan,",
  "   sops secret encryption",
  "Utilities — CLI gen, skill scaffolding, Fabric, Codex, n8n,",
  "   wrapup, beads mgmt, knowledge base, compound engineering",
  "loop — recurring tasks on interval",
  "schedule — cron-scheduled remote agents/triggers",
  "keybindings-help — customize Claude Code shortcuts",
  "simplify — review changed code for reuse, quality, efficiency",
  "less-permission-prompts — scan transcripts, build allowlist",
  "",
  "🛠 CODEX BRIDGE",
  "codex:rescue — second opinion, investigation, adversarial review",
  "codex:setup — check CLI, toggle stop-time review gate",
  "",
  "💡 Say what you want — the router picks the skill.",
  "   Triggers aren't exact — natural language works.",
].join("\n");
